service: my-serverless-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

plugins:
  - serverless-offline

functions:
  lambdaUtils:
    name: lambdaUtils-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.getUtilsDataHandler
    events:
      - http:
          path: /utils/info
          method: get
          cors: true